/**
 * Photo import script — generates src/lib/photos.ts automatically
 *
 * Usage:  npx tsx scripts/import-photos.ts
 *
 * For each image in public/photos/ it:
 *  - Reads pixel dimensions via sharp
 *  - Reads EXIF DateTimeOriginal for the year
 *  - Generates a base64 blur placeholder via plaiceholder
 *  - Preserves any existing caption / subject overrides from a sidecar JSON
 *
 * Sidecar: scripts/photo-meta.json (optional)
 * Format:  { "filename.jpg": { "caption": "...", "subject": "urmila" } }
 */

import fs from "fs";
import path from "path";
import sharp from "sharp";
import { getPlaiceholder } from "plaiceholder";
import exifr from "exifr";

const PHOTOS_DIR = path.join(process.cwd(), "public", "photos");
const OUTPUT_FILE = path.join(process.cwd(), "src", "lib", "photos.ts");
const SIDECAR_FILE = path.join(process.cwd(), "scripts", "photo-meta.json");

type Subject = "urmila" | "ajay" | "both" | "family";

interface Sidecar {
  [filename: string]: {
    caption?: string;
    subject?: Subject;
    order?: number;
  };
}

const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".JPG", ".JPEG", ".PNG"]);

function slugify(filename: string, index: number): string {
  return `photo-${String(index + 1).padStart(3, "0")}`;
}

function guessSubject(filename: string): Subject {
  const f = filename.toLowerCase();
  if (f.includes("dsc0") || f.includes("wp_") || f.includes("win_")) return "urmila";
  return "urmila";
}

async function main() {
  const sidecar: Sidecar = fs.existsSync(SIDECAR_FILE)
    ? JSON.parse(fs.readFileSync(SIDECAR_FILE, "utf-8"))
    : {};

  const files = fs
    .readdirSync(PHOTOS_DIR)
    .filter((f) => IMAGE_EXTS.has(path.extname(f)))
    .sort();

  console.log(`Found ${files.length} images in public/photos/`);

  const entries: string[] = [];

  for (let i = 0; i < files.length; i++) {
    const filename = files[i];
    const filePath = path.join(PHOTOS_DIR, filename);
    const override = sidecar[filename] ?? {};

    process.stdout.write(`  [${i + 1}/${files.length}] ${filename} … `);

    try {
      // Dimensions
      const meta = await sharp(filePath).metadata();
      const w = meta.width ?? 1;
      const h = meta.height ?? 1;
      const aspectRatio = w / h;

      // EXIF year
      let year = 2014;
      try {
        const exif = await exifr.parse(filePath, ["DateTimeOriginal", "DateTime"]);
        if (exif?.DateTimeOriginal) {
          year = new Date(exif.DateTimeOriginal).getFullYear();
        } else if (exif?.DateTime) {
          year = new Date(exif.DateTime).getFullYear();
        }
      } catch {
        // no EXIF — keep default
      }

      // Blur placeholder
      const buffer = fs.readFileSync(filePath);
      const { base64 } = await getPlaiceholder(buffer, { size: 10 });

      const slug = slugify(filename, override.order !== undefined ? override.order : i);
      const subject = override.subject ?? guessSubject(filename);
      const caption = override.caption ?? "";

      entries.push(
        `  {\n` +
        `    id: "${i + 1}", slug: "${slug}",\n` +
        `    filename: "${filename}", src: "/photos/${filename}",\n` +
        `    caption: "${caption}", year: ${year}, subject: "${subject}",\n` +
        `    aspectRatio: ${w} / ${h},\n` +
        `    blurDataURL: "${base64}",\n` +
        `  }`
      );

      console.log(`✓  (${w}×${h}, ${year})`);
    } catch (err) {
      console.log(`✗  skipped (${err instanceof Error ? err.message : err})`);
    }
  }

  const output = `import { Photo } from "@/types";

// ⚠️  Auto-generated by scripts/import-photos.ts — do not edit manually.
// To customise captions / subjects, edit scripts/photo-meta.json and re-run.

export const photos: Photo[] = [
${entries.join(",\n")}
];

export const heroPhoto =
  photos.find((p) => p.subject === "both") ?? photos[0];

export const interstitialPhoto =
  photos.find(
    (p) => p.subject === "urmila" && p.aspectRatio > 1 && p.id !== heroPhoto.id
  ) ?? photos[1];

export function getPhotoBySlug(slug: string): Photo | undefined {
  return photos.find((p) => p.slug === slug);
}

export function getAdjacentPhotos(slug: string): {
  prev: Photo | null;
  next: Photo | null;
} {
  const idx = photos.findIndex((p) => p.slug === slug);
  return {
    prev: idx > 0 ? photos[idx - 1] : null,
    next: idx < photos.length - 1 ? photos[idx + 1] : null,
  };
}
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`\n✅  Written ${entries.length} photos to ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
